### Get all books
GET http://localhost:5131/books

###

### Get a single book
GET http://localhost:5131/books/1

###

### Add a book
POST http://localhost:5131/books
Content-Type: application/json

{
    "title": "Things Fall Apart",
    "authorId": 1,
    "genreId": 1,
    "publishedYear": 1958,
    "copiesAvailable": 3
}

###

### Test validation
POST http://localhost:5131/books
Content-Type: application/json

{
    "title": "Test Book",
    "author": "Test Author",
    "publishedYear": -500,
    "copiesAvailable": -10
}

### Delete a book
DELETE http://localhost:5131/books/1


### Update a book
PUT http://localhost:5131/books/1
Content-Type: application/json

{
    "title": " Fall Apart",
    "author": "Chinua Achebe",
    "publishedYear": 1958,
    "copiesAvailable": 10
}